/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package main;

import com.formdev.flatlaf.intellijthemes.FlatArcDarkIJTheme;
import com.formdev.flatlaf.intellijthemes.FlatLightFlatIJTheme;
import com.formdev.flatlaf.intellijthemes.materialthemeuilite.FlatArcDarkContrastIJTheme;
import dao.NhanVien_dao;
import dao.TaiKhoan_DAO;
import entity.NhanVien;
import entity.TaiKhoan;
import java.awt.Color;
import javax.swing.JFrame;
import javax.swing.table.DefaultTableModel;

import java.awt.geom.RoundRectangle2D;
import java.rmi.Naming;
import java.util.ArrayList;
import java.util.List;
import java.sql.SQLException;
//import java.sql.Date;
import java.util.Date;

import javax.swing.JOptionPane;
import javax.swing.JPopupMenu;
import javax.swing.UIManager;
import static main.Login_form.tk;

/**
 *
 * @author HP
 */
public class GD_Chinh extends javax.swing.JFrame {

    NhanVien_dao nvDao;
    TaiKhoan_DAO tkDao;

//    public GD_Chinh() {
//         initComponents();
//        setResizable(false);
//        setLocationRelativeTo(null);
//        setDefaultCloseOperation(EXIT_ON_CLOSE);
//         setShape(new RoundRectangle2D.Double(0, 0, getWidth(), getHeight(), 30, 30));
//          tab_lk1.setBackground(new Color(234,90,90));
//          jLabel25.setForeground(Color.white);
//          try {
//            String urlNv = "rmi://192.168.1.3:6881/nvDao";
//            nvDao = (NhanVien_dao) Naming.lookup(urlNv);
//        } catch (Exception e) {
//        }
//    }
    
    public GD_Chinh( TaiKhoan tK) {
         initComponents();
        setResizable(false);
        setLocationRelativeTo(null);
        setDefaultCloseOperation(EXIT_ON_CLOSE);
         setShape(new RoundRectangle2D.Double(0, 0, getWidth(), getHeight(), 30, 30));
          tab_lk1.setBackground(new Color(234,90,90));
          jLabel25.setForeground(Color.white);
          try {
            String urlNv = "rmi://192.168.1.3:6881/nvDao";
            nvDao = (NhanVien_dao) Naming.lookup(urlNv);
            
            String urlTk = "rmi://192.168.1.3:6881/tkDao";
            tkDao = (TaiKhoan_DAO) Naming.lookup(urlTk);
        } catch (Exception e) {
        }
          tk = new TaiKhoan(tK);
          System.out.println("nhan vien"+tk);
          hienThiTTNv();
          tab_lk1.setBackground(new Color(234,90,90));
          jLabel25.setForeground(Color.white);
    }
    public void hienThiTTNv(){
        try {
            NhanVien nv = nvDao.getNV(tk.getNhanVien().getMaNv());
            jLabel_tt.setText(nv.getTenNv());
        } catch (Exception e) {
        }
    }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPopupMenu1 = new javax.swing.JPopupMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        jp_main = new javax.swing.JPanel();
        jp_left_img = new javax.swing.JPanel();
        tab_lk = new javax.swing.JPanel();
        jLabel30 = new javax.swing.JLabel();
        jLabel33 = new javax.swing.JLabel();
        tab_lk1 = new javax.swing.JPanel();
        jLabel25 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        tab_lk2 = new javax.swing.JPanel();
        jLabel31 = new javax.swing.JLabel();
        jLabel34 = new javax.swing.JLabel();
        tab_hd = new javax.swing.JPanel();
        jLabel40 = new javax.swing.JLabel();
        jLabel36 = new javax.swing.JLabel();
        tab_thtoan = new javax.swing.JPanel();
        jLabel41 = new javax.swing.JLabel();
        jLabel39 = new javax.swing.JLabel();
        tab_home = new javax.swing.JPanel();
        jLabel28 = new javax.swing.JLabel();
        jLabel29 = new javax.swing.JLabel();
        jp_header = new javax.swing.JPanel();
        tab_tt = new javax.swing.JPanel();
        jLabel_tt = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        frmHome1 = new main.FrmHome();
        frmBanHang1 = new main.FrmBanHang();
        frmLinhKien1 = new main.FrmLinhKien();
        frmKhachHang1 = new main.FrmKhachHang();
        frmGioHang1 = new main.FrmGioHang();
        frmHoaDon1 = new main.FrmHoaDon();
        frmTTTK1 = new main.FrmTTTK();

        jPopupMenu1.setComponentPopupMenu(jPopupMenu1);

        jMenuItem1.setForeground(new java.awt.Color(51, 51, 51));
        jMenuItem1.setText("Thông Tin Tài Khoản.");
        jMenuItem1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenuItem1MouseClicked(evt);
            }
        });
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jPopupMenu1.add(jMenuItem1);

        jMenuItem2.setForeground(new java.awt.Color(255, 102, 102));
        jMenuItem2.setText("Đăng Xuất");
        jMenuItem2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenuItem2MouseClicked(evt);
            }
        });
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        jPopupMenu1.add(jMenuItem2);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        jp_main.setBackground(new java.awt.Color(255, 255, 255));
        jp_main.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jp_left_img.setBackground(new java.awt.Color(49, 53, 65));

        tab_lk.setBackground(new java.awt.Color(49, 53, 65));
        tab_lk.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tab_lkMouseClicked(evt);
            }
        });

        jLabel30.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel30.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/circuit.png"))); // NOI18N

        jLabel33.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel33.setForeground(new java.awt.Color(102, 112, 126));
        jLabel33.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel33.setText("Linh Kiện");

        javax.swing.GroupLayout tab_lkLayout = new javax.swing.GroupLayout(tab_lk);
        tab_lk.setLayout(tab_lkLayout);
        tab_lkLayout.setHorizontalGroup(
            tab_lkLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel30, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jLabel33, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        tab_lkLayout.setVerticalGroup(
            tab_lkLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tab_lkLayout.createSequentialGroup()
                .addComponent(jLabel30, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel33, javax.swing.GroupLayout.DEFAULT_SIZE, 23, Short.MAX_VALUE))
        );

        tab_lk1.setBackground(new java.awt.Color(49, 53, 65));
        tab_lk1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tab_lk1MouseClicked(evt);
            }
        });

        jLabel25.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel25.setForeground(new java.awt.Color(102, 112, 126));
        jLabel25.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel25.setText("Home");

        jLabel17.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel17.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/home (1).png"))); // NOI18N

        javax.swing.GroupLayout tab_lk1Layout = new javax.swing.GroupLayout(tab_lk1);
        tab_lk1.setLayout(tab_lk1Layout);
        tab_lk1Layout.setHorizontalGroup(
            tab_lk1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel25, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jLabel17, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        tab_lk1Layout.setVerticalGroup(
            tab_lk1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tab_lk1Layout.createSequentialGroup()
                .addComponent(jLabel17, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel25, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        tab_lk2.setBackground(new java.awt.Color(49, 53, 65));
        tab_lk2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tab_lk2MouseClicked(evt);
            }
        });

        jLabel31.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel31.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/customer.png"))); // NOI18N

        jLabel34.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel34.setForeground(new java.awt.Color(102, 112, 126));
        jLabel34.setText("Khách Hàng");

        javax.swing.GroupLayout tab_lk2Layout = new javax.swing.GroupLayout(tab_lk2);
        tab_lk2.setLayout(tab_lk2Layout);
        tab_lk2Layout.setHorizontalGroup(
            tab_lk2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tab_lk2Layout.createSequentialGroup()
                .addGroup(tab_lk2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel34, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel31, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        tab_lk2Layout.setVerticalGroup(
            tab_lk2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tab_lk2Layout.createSequentialGroup()
                .addComponent(jLabel31, javax.swing.GroupLayout.DEFAULT_SIZE, 38, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel34))
        );

        tab_hd.setBackground(new java.awt.Color(49, 53, 65));
        tab_hd.setForeground(new java.awt.Color(204, 204, 255));
        tab_hd.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tab_hdMouseClicked(evt);
            }
        });

        jLabel40.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel40.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/shopping-cart (1).png"))); // NOI18N

        jLabel36.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel36.setForeground(new java.awt.Color(102, 112, 126));
        jLabel36.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel36.setText("Giỏ Hàng");

        javax.swing.GroupLayout tab_hdLayout = new javax.swing.GroupLayout(tab_hd);
        tab_hd.setLayout(tab_hdLayout);
        tab_hdLayout.setHorizontalGroup(
            tab_hdLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel36, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jLabel40, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        tab_hdLayout.setVerticalGroup(
            tab_hdLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, tab_hdLayout.createSequentialGroup()
                .addComponent(jLabel40, javax.swing.GroupLayout.DEFAULT_SIZE, 38, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel36))
        );

        tab_thtoan.setBackground(new java.awt.Color(49, 53, 65));
        tab_thtoan.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tab_thtoanMouseClicked(evt);
            }
        });

        jLabel41.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel41.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/bill.png"))); // NOI18N

        jLabel39.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel39.setForeground(new java.awt.Color(102, 112, 126));
        jLabel39.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel39.setText("Hóa Đơn");

        javax.swing.GroupLayout tab_thtoanLayout = new javax.swing.GroupLayout(tab_thtoan);
        tab_thtoan.setLayout(tab_thtoanLayout);
        tab_thtoanLayout.setHorizontalGroup(
            tab_thtoanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel39, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jLabel41, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        tab_thtoanLayout.setVerticalGroup(
            tab_thtoanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tab_thtoanLayout.createSequentialGroup()
                .addComponent(jLabel41, javax.swing.GroupLayout.DEFAULT_SIZE, 38, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel39))
        );

        tab_home.setBackground(new java.awt.Color(49, 53, 65));
        tab_home.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tab_homeMouseClicked(evt);
            }
        });

        jLabel28.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel28.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/shopping-bag.png"))); // NOI18N

        jLabel29.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel29.setForeground(new java.awt.Color(102, 112, 126));
        jLabel29.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel29.setText("Bán Hàng");

        javax.swing.GroupLayout tab_homeLayout = new javax.swing.GroupLayout(tab_home);
        tab_home.setLayout(tab_homeLayout);
        tab_homeLayout.setHorizontalGroup(
            tab_homeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel28, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jLabel29, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        tab_homeLayout.setVerticalGroup(
            tab_homeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tab_homeLayout.createSequentialGroup()
                .addComponent(jLabel28, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel29, javax.swing.GroupLayout.DEFAULT_SIZE, 23, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jp_left_imgLayout = new javax.swing.GroupLayout(jp_left_img);
        jp_left_img.setLayout(jp_left_imgLayout);
        jp_left_imgLayout.setHorizontalGroup(
            jp_left_imgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jp_left_imgLayout.createSequentialGroup()
                .addGroup(jp_left_imgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jp_left_imgLayout.createSequentialGroup()
                        .addGroup(jp_left_imgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(tab_thtoan, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(tab_hd, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(tab_lk1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(tab_lk2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(tab_lk, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(tab_home, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jp_left_imgLayout.setVerticalGroup(
            jp_left_imgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jp_left_imgLayout.createSequentialGroup()
                .addGap(75, 75, 75)
                .addComponent(tab_lk1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addComponent(tab_home, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addComponent(tab_lk, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(34, 34, 34)
                .addComponent(tab_lk2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(40, 40, 40)
                .addComponent(tab_hd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addComponent(tab_thtoan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jp_main.add(jp_left_img, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 80, 741));

        jp_header.setBackground(new java.awt.Color(255, 255, 255));
        jp_header.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(90, 103, 121)));

        tab_tt.setBackground(new java.awt.Color(255, 255, 255));
        tab_tt.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tab_ttMouseClicked(evt);
            }
        });

        jLabel_tt.setBackground(new java.awt.Color(255, 255, 255));
        jLabel_tt.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel_tt.setForeground(new java.awt.Color(0, 0, 0));
        jLabel_tt.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel_tt.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/user (1).png"))); // NOI18N

        javax.swing.GroupLayout tab_ttLayout = new javax.swing.GroupLayout(tab_tt);
        tab_tt.setLayout(tab_ttLayout);
        tab_ttLayout.setHorizontalGroup(
            tab_ttLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tab_ttLayout.createSequentialGroup()
                .addComponent(jLabel_tt, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 19, Short.MAX_VALUE))
        );
        tab_ttLayout.setVerticalGroup(
            tab_ttLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tab_ttLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel_tt, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jButton1.setBackground(new java.awt.Color(255, 255, 255));
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/sign-out (4).png"))); // NOI18N
        jButton1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton1MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jButton1MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jButton1MouseExited(evt);
            }
        });

        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/question (1).png"))); // NOI18N
        jButton2.setContentAreaFilled(false);
        jButton2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/gear (1).png"))); // NOI18N
        jButton3.setContentAreaFilled(false);
        jButton3.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton3MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jButton3MouseEntered(evt);
            }
        });

        javax.swing.GroupLayout jp_headerLayout = new javax.swing.GroupLayout(jp_header);
        jp_header.setLayout(jp_headerLayout);
        jp_headerLayout.setHorizontalGroup(
            jp_headerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jp_headerLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(tab_tt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButton3)
                .addGap(18, 18, 18)
                .addComponent(jButton2)
                .addGap(18, 18, 18)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28))
        );
        jp_headerLayout.setVerticalGroup(
            jp_headerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jButton2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jButton3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jp_headerLayout.createSequentialGroup()
                .addComponent(tab_tt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        jp_main.add(jp_header, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 0, 1150, -1));

        jTabbedPane1.setBackground(new java.awt.Color(255, 255, 255));
        jTabbedPane1.addTab("tab2", frmHome1);
        jTabbedPane1.addTab("tab1", frmBanHang1);
        jTabbedPane1.addTab("tab3", frmLinhKien1);
        jTabbedPane1.addTab("tab4", frmKhachHang1);
        jTabbedPane1.addTab("tab5", frmGioHang1);
        jTabbedPane1.addTab("tab6", frmHoaDon1);
        jTabbedPane1.addTab("tab7", frmTTTK1);

        jp_main.add(jTabbedPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, -9, -1, 750));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jp_main, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jp_main, javax.swing.GroupLayout.PREFERRED_SIZE, 700, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    
    
    

    private void tab_homeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tab_homeMouseClicked

    	frmBanHang1.reload();
        jTabbedPane1.setSelectedIndex(1);
        tab_tt.setBackground(Color.white);
        tab_lk.setBackground(new Color(49,53,65));
        tab_hd.setBackground(new Color(49,53,65));
        tab_home.setBackground(new Color(234,90,90));
        jLabel25.setForeground(new Color(102,112,126));
        jLabel29.setForeground(Color.white);
        jLabel33.setForeground(new Color(102,112,126));
        jLabel34.setForeground(new Color(102,112,126));
        tab_lk1.setBackground(new Color(49,53,65));
        tab_lk2.setBackground(new Color(49,53,65));
        tab_thtoan.setBackground(new Color(49,53,65));
       
        jLabel36.setForeground(new Color(102,112,126));
        jLabel39.setForeground(new Color(102,112,126));
        

    }//GEN-LAST:event_tab_homeMouseClicked

    private void tab_lkMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tab_lkMouseClicked
        // TODO add your handling code here:
       jTabbedPane1.setSelectedIndex(2);
        tab_tt.setBackground(Color.white);
        tab_home.setBackground(new Color(49,53,65));
        tab_hd.setBackground(new Color(49,53,65));
        tab_thtoan.setBackground(new Color(49,53,65));
        tab_lk.setBackground(new Color(234,90,90));
        jLabel25.setForeground(new Color(102,112,126));
        jLabel29.setForeground(new Color(102,112,126));
        jLabel33.setForeground(Color.white);
        jLabel34.setForeground(new Color(102,112,126));
        tab_lk1.setBackground(new Color(49,53,65));
        tab_lk2.setBackground(new Color(49,53,65));
       frmLinhKien1.reload();
        jLabel36.setForeground(new Color(102,112,126));
        jLabel39.setForeground(new Color(102,112,126));

    }//GEN-LAST:event_tab_lkMouseClicked

    private void tab_hdMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tab_hdMouseClicked
        // TODO add your handling code here:
       jTabbedPane1.setSelectedIndex(4);
        tab_tt.setBackground(Color.white);
        tab_lk.setBackground(new Color(49,53,65));
        tab_home.setBackground(new Color(49,53,65));
        tab_thtoan.setBackground(new Color(49,53,65));
        tab_hd.setBackground(new Color(234,90,90));
        jLabel25.setForeground(new Color(102,112,126));
        jLabel29.setForeground(new Color(102,112,126));
        jLabel33.setForeground(new Color(102,112,126));
        jLabel34.setForeground(new Color(102,112,126));
        tab_lk1.setBackground(new Color(49,53,65));
        tab_lk2.setBackground(new Color(49,53,65));
        
        jLabel36.setForeground(Color.white);
        jLabel39.setForeground(new Color(102,112,126));
    }//GEN-LAST:event_tab_hdMouseClicked

    private void tab_ttMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tab_ttMouseClicked

        tab_home.setBackground(new Color(49,53,65));
        tab_lk.setBackground(new Color(49,53,65));
        tab_hd.setBackground(new Color(49,53,65));
        tab_thtoan.setBackground(new Color(49,53,65));
        tab_tt.setBackground(Color.white);
        tab_lk1.setBackground(new Color(49,53,65));
        tab_lk2.setBackground(new Color(49,53,65));
       jPopupMenu1.show(jLabel_tt, 0, jLabel_tt.getHeight());
        
    }//GEN-LAST:event_tab_ttMouseClicked

    private void tab_thtoanMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tab_thtoanMouseClicked
        // TODO add your handling code here:
        frmHoaDon1.reload();
        jTabbedPane1.setSelectedIndex(5);
        tab_home.setBackground(new Color(49,53,65));
        tab_lk.setBackground(new Color(49,53,65));
        tab_hd.setBackground(new Color(49,53,65));
        tab_tt.setBackground(Color.white);
        tab_thtoan.setBackground(new Color(234,90,90));
        jLabel25.setForeground(new Color(102,112,126));
        jLabel29.setForeground(new Color(102,112,126));
        jLabel33.setForeground(new Color(102,112,126));
        jLabel34.setForeground(new Color(102,112,126));
        tab_lk1.setBackground(new Color(49,53,65));
        tab_lk2.setBackground(new Color(49,53,65));
      
        jLabel36.setForeground(new Color(102,112,126));
        jLabel39.setForeground(Color.white);
        
    }//GEN-LAST:event_tab_thtoanMouseClicked

    private void tab_lk1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tab_lk1MouseClicked
        frmHome1.reload();
    	jTabbedPane1.setSelectedIndex(0);
         tab_thtoan.setBackground(new Color(49,53,65));
        tab_tt.setBackground(Color.white);
        tab_lk.setBackground(new Color(49,53,65));
        tab_hd.setBackground(new Color(49,53,65));
        tab_home.setBackground(new Color(49,53,65));
        jLabel29.setForeground(new Color(102,112,126));
        jLabel25.setForeground(Color.white);
        jLabel33.setForeground(new Color(102,112,126));
        jLabel34.setForeground(new Color(102,112,126));
        tab_lk1.setBackground(new Color(234,90,90));
        tab_lk2.setBackground(new Color(49,53,65));
       
        jLabel36.setForeground(new Color(102,112,126));
        jLabel39.setForeground(new Color(102,112,126));
    }//GEN-LAST:event_tab_lk1MouseClicked

    private void tab_lk2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tab_lk2MouseClicked
        jTabbedPane1.setSelectedIndex(3);
        tab_tt.setBackground(Color.white);
         tab_thtoan.setBackground(new Color(49,53,65));
        tab_lk.setBackground(new Color(49,53,65));
        tab_hd.setBackground(new Color(49,53,65));
        tab_home.setBackground(new Color(49,53,65));
        jLabel25.setForeground(new Color(102,112,126));
        jLabel34.setForeground(Color.white);
        jLabel33.setForeground(new Color(102,112,126));
       
        tab_lk1.setBackground(new Color(49,53,65));
        tab_lk2.setBackground(new Color(234,90,90));
       
        jLabel36.setForeground(new Color(102,112,126));
        jLabel39.setForeground(new Color(102,112,126));
        frmKhachHang1.reload();
    }//GEN-LAST:event_tab_lk2MouseClicked

    private void jButton1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MouseEntered
       jButton1.setBackground(new Color(234,90,90));
    }//GEN-LAST:event_jButton1MouseEntered

    private void jButton1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MouseExited
        jButton1.setBackground(Color.white);
    }//GEN-LAST:event_jButton1MouseExited

    private void jButton1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MouseClicked
        int lick = JOptionPane.showConfirmDialog(null, "Bạn Có Muốn Thoát Khỏi Chương Trình Hay Không?", "Thông Báo", 2);
        if (lick == JOptionPane.OK_OPTION) {
//            System.exit(0);
           this.setVisible(false);
            new Login_form().setVisible(true);
            tk.setTrangThai("off");
            try {
            tkDao.capNhatTrangThai(tk);
        } catch (Exception e) {
        }
        } else {
            if (lick == JOptionPane.CANCEL_OPTION) {
                this.setVisible(true);
            }
        }
    }//GEN-LAST:event_jButton1MouseClicked

    private void jButton3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton3MouseClicked
       
    }//GEN-LAST:event_jButton3MouseClicked

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        jTabbedPane1.setSelectedIndex(6);
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void jButton3MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton3MouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton3MouseEntered

    private void jMenuItem1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenuItem1MouseClicked
        
    }//GEN-LAST:event_jMenuItem1MouseClicked

    private void jMenuItem2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenuItem2MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem2MouseClicked

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed

//            System.exit(0);
            this.setVisible(false);
            new Login_form().setVisible(true);
            tk.setTrangThai("off");
            try {
            tkDao.capNhatTrangThai(tk);
        } catch (Exception e) {
        }
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        try {
            FlatLightFlatIJTheme.setup();
        } catch (Exception e) {
            e.printStackTrace();
        }

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {

                TaiKhoan tk = new TaiKhoan();
                new GD_Chinh(tk).setVisible(true);
//                new GD_Chinh().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private main.FrmBanHang frmBanHang1;
    private main.FrmGioHang frmGioHang1;
    private main.FrmHoaDon frmHoaDon1;
    private main.FrmHome frmHome1;
    private main.FrmKhachHang frmKhachHang1;
    private main.FrmLinhKien frmLinhKien1;
    private main.FrmTTTK frmTTTK1;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel36;
    private javax.swing.JLabel jLabel39;
    private javax.swing.JLabel jLabel40;
    private javax.swing.JLabel jLabel41;
    public javax.swing.JLabel jLabel_tt;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JPopupMenu jPopupMenu1;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JPanel jp_header;
    private javax.swing.JPanel jp_left_img;
    private javax.swing.JPanel jp_main;
    private javax.swing.JPanel tab_hd;
    private javax.swing.JPanel tab_home;
    private javax.swing.JPanel tab_lk;
    private javax.swing.JPanel tab_lk1;
    private javax.swing.JPanel tab_lk2;
    private javax.swing.JPanel tab_thtoan;
    public javax.swing.JPanel tab_tt;
    // End of variables declaration//GEN-END:variables
}
