/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package main;

import com.formdev.flatlaf.intellijthemes.FlatArcDarkIJTheme;
import com.formdev.flatlaf.intellijthemes.FlatArcDarkIJTheme;
import com.formdev.flatlaf.intellijthemes.FlatLightFlatIJTheme;
import com.formdev.flatlaf.intellijthemes.materialthemeuilite.FlatArcDarkContrastIJTheme;
import dao.NhanVien_dao;
import dao.TaiKhoan_DAO;
import main.GD_Chinh;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.JTextField;
import javax.swing.JOptionPane;
import entity.TaiKhoan;
import entity.NhanVien;
import java.awt.Color;
import java.awt.geom.RoundRectangle2D;
import java.rmi.Naming;

/**
 *
 * @author HP
 */
public class Login_form extends javax.swing.JFrame {

//    private Connection conn = null;
//    private PreparedStatement pst = null;    
//    private ResultSet rs = null;
    public static TaiKhoan tk;
    private GD_Chinh Gd;
    private NhanVien nv;
    private Login_form lg;
    TaiKhoan_DAO tkDao;
    NhanVien_dao nvDao;

    public Login_form() {
        initComponents();
        setResizable(false);
        setLocationRelativeTo(null);
        setDefaultCloseOperation(EXIT_ON_CLOSE);
        setShape(new RoundRectangle2D.Double(0, 0, getWidth(), getHeight(), 30, 30));
        try {
            String urlTk = "rmi://192.168.1.3:6881/tkDao";
            tkDao = (TaiKhoan_DAO) Naming.lookup(urlTk);

            String urlNv = "rmi://192.168.1.3:6881/nvDao";
            nvDao = (NhanVien_dao) Naming.lookup(urlNv);
        } catch (Exception e) {
           
        }
    }

    private boolean checkNull() {
        boolean kq = true;
        if (this.jt_TenDN.getText().length() == 0) {
            lblStatus.setText("Bạn chưa nhập tên đăng nhập!");
            return false;
        }
        if (String.valueOf(this.jpass_mk.getPassword()).length() == 0) {
            lblStatus.setText("Bạn chưa nhập mật khẩu!");
            return false;
        }
        return kq;
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jlb_hethong = new javax.swing.JLabel();
        jlb_TenDN = new javax.swing.JLabel();
        jlb_Mk = new javax.swing.JLabel();
        jt_TenDN = new javax.swing.JTextField();
        jb_DN = new javax.swing.JButton();
        jc_show = new javax.swing.JCheckBox();
        jbl_show = new javax.swing.JLabel();
        jpass_mk = new javax.swing.JPasswordField();
        lblStatus = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jlb_hethong.setBackground(new java.awt.Color(255, 255, 255));
        jlb_hethong.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jlb_hethong.setForeground(new java.awt.Color(90, 103, 121));
        jlb_hethong.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jlb_hethong.setText("ĐĂNG NHẬP");
        jPanel1.add(jlb_hethong, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 10, 150, 30));

        jlb_TenDN.setBackground(new java.awt.Color(255, 255, 255));
        jlb_TenDN.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jlb_TenDN.setForeground(new java.awt.Color(0, 0, 0));
        jlb_TenDN.setText("Tên Đăng Nhập:");
        jPanel1.add(jlb_TenDN, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 60, -1, -1));

        jlb_Mk.setBackground(new java.awt.Color(255, 255, 255));
        jlb_Mk.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jlb_Mk.setForeground(new java.awt.Color(0, 0, 0));
        jlb_Mk.setText("Mật Khẩu:");
        jPanel1.add(jlb_Mk, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 130, -1, -1));

        jt_TenDN.setBackground(new java.awt.Color(255, 255, 255));
        jt_TenDN.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jt_TenDN.setForeground(new java.awt.Color(0, 0, 0));
        jt_TenDN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jt_TenDNActionPerformed(evt);
            }
        });
        jPanel1.add(jt_TenDN, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 80, 260, 30));

        jb_DN.setBackground(new java.awt.Color(13, 110, 253));
        jb_DN.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jb_DN.setForeground(new java.awt.Color(255, 255, 255));
        jb_DN.setText("ĐĂNG NHẬP");
        jb_DN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jb_DNActionPerformed(evt);
            }
        });
        jPanel1.add(jb_DN, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 240, 260, 40));

        jc_show.setBackground(new java.awt.Color(255, 255, 255));
        jc_show.setForeground(new java.awt.Color(0, 0, 0));
        jc_show.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jc_showActionPerformed(evt);
            }
        });
        jPanel1.add(jc_show, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 190, -1, -1));

        jbl_show.setBackground(new java.awt.Color(255, 255, 255));
        jbl_show.setForeground(new java.awt.Color(0, 0, 0));
        jbl_show.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images_menu/eye-16.png"))); // NOI18N
        jPanel1.add(jbl_show, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 190, -1, -1));

        jpass_mk.setBackground(new java.awt.Color(255, 255, 255));
        jpass_mk.setForeground(new java.awt.Color(0, 0, 0));
        jpass_mk.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jpass_mkActionPerformed(evt);
            }
        });
        jPanel1.add(jpass_mk, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 150, 260, 30));

        lblStatus.setFont(new java.awt.Font("Segoe UI Semibold", 0, 14)); // NOI18N
        lblStatus.setForeground(new java.awt.Color(255, 51, 51));
        lblStatus.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblStatus.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        lblStatus.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jPanel1.add(lblStatus, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 290, 330, 40));

        jLabel1.setIcon(new javax.swing.ImageIcon("D:\\DT_JavaPhanTan\\QLLK_Clinet\\icon\\1 1.png")); // NOI18N
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 270, 330));

        jButton2.setIcon(new javax.swing.ImageIcon("D:\\DT_JavaPhanTan\\QLLK_Clinet\\icon\\cancel (1).png")); // NOI18N
        jButton2.setContentAreaFilled(false);
        jButton2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton2MouseClicked(evt);
            }
        });
        jPanel1.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 0, 20, 40));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 600, 330));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jt_TenDNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jt_TenDNActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jt_TenDNActionPerformed

    private void jb_DNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jb_DNActionPerformed
        // TODO add your handling code here:
        if (checkNull()) {
            String tenDn = jt_TenDN.getText().trim();
            String mk = String.valueOf(jpass_mk.getPassword());
            
            try {
                tk = tkDao.getTkByTenDNvsMK(tenDn, mk);
            } catch (Exception e) {
            }
            String tt = tk.getTrangThai();
            System.out.println("tendn" + tenDn);
            System.out.println("mk" + mk);
            System.out.println("taikhon" + tk);
            System.out.println("Trang thai"+tt);
            
            if (tk.getTenDN() != null) {
                if (tt.equals("off")) {
                    lblStatus.setText("Đăng Nhập Thành Công...");
                    lblStatus.setForeground(new Color(40,189,139));
                    GD_Chinh gd = new GD_Chinh(tk);
                    
                    this.setVisible(false);
                    gd.setVisible(true);
                    tk.setTrangThai("on");
                    
                    try {
                        tkDao.capNhatTrangThai(tk);
                    } catch (Exception e) {
                    }
                } else {
                    lblStatus.setText("Tài khoản của bạn đang đăng nhập!");
                }
            } else {
                lblStatus.setText("Bạn đã nhập sai tên đăng nhập hoặc mật khẩu!");
            }

        }
    }//GEN-LAST:event_jb_DNActionPerformed

    private void jc_showActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jc_showActionPerformed
        // TODO add your handling code here:
        if (jc_show.isSelected()) {
            jpass_mk.setEchoChar((char) 0);

        } else {
            jpass_mk.setEchoChar('*');
        }

    }//GEN-LAST:event_jc_showActionPerformed

    private void jpass_mkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jpass_mkActionPerformed
        if (checkNull()) {
            String tenDn = jt_TenDN.getText().trim();
            String mk = String.valueOf(jpass_mk.getPassword());
            
            try {
                tk = tkDao.getTkByTenDNvsMK(tenDn, mk);
            } catch (Exception e) {
            }
            String tt = tk.getTrangThai();
            System.out.println("tendn" + tenDn);
            System.out.println("mk" + mk);
            System.out.println("taikhon" + tk);
            System.out.println("Trang thai"+tt);
            
            if (tk.getTenDN() != null) {
                if (tt.equals("off")) {
                     
                    GD_Chinh gd = new GD_Chinh(tk);
                    lblStatus.setText("Đăng Nhập Thành Công...");
                     lblStatus.setForeground(new Color(40,189,139));
                    this.setVisible(false);
                    gd.setVisible(true);
                    tk.setTrangThai("on");
                    try {
                        tkDao.capNhatTrangThai(tk);
                    } catch (Exception e) {
                    }
                } else {
                    lblStatus.setText("Tài khoản của bạn đang đăng nhập!");
                }
            } else {
                lblStatus.setText("Bạn đã nhập sai tên đăng nhập hoặc mật khẩu!");
            }

        }
    }//GEN-LAST:event_jpass_mkActionPerformed

    private void jButton2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton2MouseClicked
        System.exit(0);
    }//GEN-LAST:event_jButton2MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        try {
            FlatLightFlatIJTheme.setup();
        } catch (Exception e) {
            e.printStackTrace();
        }

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Login_form().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton jb_DN;
    private javax.swing.JLabel jbl_show;
    private javax.swing.JCheckBox jc_show;
    private javax.swing.JLabel jlb_Mk;
    private javax.swing.JLabel jlb_TenDN;
    private javax.swing.JLabel jlb_hethong;
    private javax.swing.JPasswordField jpass_mk;
    public javax.swing.JTextField jt_TenDN;
    private javax.swing.JLabel lblStatus;
    // End of variables declaration//GEN-END:variables
}
